project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "doc/App_A.qmd"
    - "doc/App_B.qmd"
    - "doc/App_C.qmd"
    - "doc/App_D.qmd"
    - "doc/App_E.qmd"

engine: knitr

website:
  # favicon: images/logo.png
  sidebar:
    pinned: true
    search: true
    collapse-level: 0
    tools: 
      - icon: images/logo.png
        href: https://sprfmo.int
      - icon: github
        href: https://github.com/sprfmo/SCW15_report
        text: "SCW15 workshop report"
    contents:
      - href: index.qmd
        text: Report
      - section: "Appendices"
        contents:
          - href: doc/App_A.qmd
            text: Participants
          - href: doc/App_B.qmd
            text: Agenda
          - href: doc/App_C.qmd
            text: Minutes
          - href: doc/App_D.qmd
            text: External experts
          - href: doc/App_E.qmd
            text: Misc. notes
      - section: "Other formats"
        contents:
          - file: index.pdf
            text: SCW15 PDF
          - file: index.epub
            text: SCW15 EPUB
          - file: index.docx
            text: SCW15 Word
#             
# website:
#   page-navigation: true
#   title: "SCW15 Report"
#   site-url: "https://sprfmo.github.io/SCW15_report"
#   repo-url: "https://github.com/sprfmo/SCW15_report"
#   repo-actions: [edit, source, issue]
#   favicon: images/logo.png
# 
#   sidebar:
#     logo: images/logo.png   # shows logo in top left corner
#     pinned: true
#     align: left
#     search: true
#     collapse-level: 0
#     tools: 
#       - icon: github
#         href: https://github.com/sprfmo/SCW15_report
#         text: "SCW15 workshop report"
#     contents:
#       - href: index.qmd
#         text: Report
#       - section: "Appendices"
#         contents:
#           - href: doc/App_A.qmd
#             text: Participants
#           - href: doc/App_B.qmd
#             text: Agenda
#           - href: doc/App_C.qmd
#             text: Minutes
#           - href: doc/App_D.qmd
#             text: External experts
#           - href: doc/App_E.qmd
#             text: Misc. notes

format:
  html:
    title-block-banner: true   # shows title & logo at the top
    title-block-style: none    # disables default banner styling
    lightbox: true
    html-math-method:
      method: mathjax
      url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          tex: {
            inlineMath: [['\\(', '\\)'], ['$', '$']],
            displayMath: [['\\[', '\\]'], ['$$', '$$']],
            processEscapes: true
          }
        };
        </script>
    theme:
      light: [cosmo] 
      dark: [darkly]
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-title: 'Contents'
    toc-location: right
    fig-cap-location: margin
    tbl-cap-location: margin
    embed-resources: true
    code-summary: "Show the code"
    code-fold: true

  pdf:
    documentclass: scrreprt
    papersize: letter
    header-includes:
      - \counterwithout{figure}{chapter}

date: now
date-format: "YYYY-MM-DD"
css: mystyle.css
bibliography: references.bib